### ISSUE TITLE
Stylint should be included

### ISSUE THREAD

**Issue by celsomiranda** [AtomLinter/linter-stylint#2]
If you look at `linter-jshint` they're including `jshint` with the package by making it a dependency.

**Comment by matthojo** [comment]
This was removed in https://github.com/AtomLinter/linter-stylint/commit/999f9c9b99cd2224de3f5f9b9138f0f31852f6ee because Stylint currently has dependencies which are not compatible with Atom.

Resolving to the global install also means Atom Linter will use the version of the Stylint installed globally (incase you didn't want the latest), and saves this linter from being updated after every Stylint update - unless the Stylint update forces a linter update.

**Comment by matthojo** [comment]
Note: This does not mean it will not happen in the future if Stylint removes the incompatible dependencies.
